name: matest_blog
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  fluent_ui: 4.6.2
  flutter_highlight: 0.7.0
  firebase_core: 2.13.1
  flutter_launcher_icons: 0.13.1
  flutter_acrylic: ^1.1.3
  system_theme: ^2.2.0
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: FiraCode
      fonts:
        - asset: assets/fonts/FiraCode-Regular.ttf

  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_foreground : "assets/images/logo.png"
  adaptive_icon_background: "assets/images/logo.png"