// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiRf9vlLdyJD5vpm_y6cL3l-Y3Gg9a3to',
    appId: '1:242055315972:web:719b6ec1ec1aaa04a92b51',
    messagingSenderId: '242055315972',
    projectId: 'matest-blog',
    authDomain: 'matest-blog.firebaseapp.com',
    storageBucket: 'matest-blog.appspot.com',
    measurementId: 'G-T6STHPNKY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDyvl44DXzfJzDe-Lw99t8FFxAQG44LZ8',
    appId: '1:242055315972:android:20bb679cdaa3284da92b51',
    messagingSenderId: '242055315972',
    projectId: 'matest-blog',
    storageBucket: 'matest-blog.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBFFXUJAUCXWLOHnkrk-ix4pXm5NyrPXo',
    appId: '1:242055315972:ios:029baa080adf2661a92b51',
    messagingSenderId: '242055315972',
    projectId: 'matest-blog',
    storageBucket: 'matest-blog.appspot.com',
    iosClientId: '242055315972-g6iurfhgq4p4fcm9otgv26hifptlsqia.apps.googleusercontent.com',
    iosBundleId: 'com.scoor.matestBlog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBFFXUJAUCXWLOHnkrk-ix4pXm5NyrPXo',
    appId: '1:242055315972:ios:81746d6414cd15fca92b51',
    messagingSenderId: '242055315972',
    projectId: 'matest-blog',
    storageBucket: 'matest-blog.appspot.com',
    iosClientId: '242055315972-7aqlkaviej05agh94uj8cvrrlvaiaouj.apps.googleusercontent.com',
    iosBundleId: 'com.scoor.matestBlog.RunnerTests',
  );
}
